%format model     = "\textbf{model}"
%format partial   = "\textbf{partial}"
%format flow      = "\textbf{flow}"
%format constant  = "\textbf{constant}"
%format equation  = "\textbf{equation}"
%format end       = "\textbf{end}"
%format connector = "\textbf{connector}"
%format parameter = "\textbf{parameter}"
%format protected = "\textbf{protected}"
%format extends   = "\textbf{extends}"
%format connect   = "\textbf{connect}"
%format .         = "."

%format Real      = "Real"